language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8         # this works for Linux but is ignored on macOS or Windows
      dist: xenial
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      before_script:
        - flake8 readlif
    - name: "Python 3.6.7 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Pypy 3.5 on Xenial Linux"
      python: "pypy3"       # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.2
        - python -m pip install --upgrade pip
        - python -m pip install --user unittest2
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install unittest2
  - pip3 install flake8
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 setup.py test || python setup.py test

deploy:
  provider: pypi
  edge: true
  username: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true